apiVersion: v1
kind: Secret
metadata:
    name: services-secrets
type: Opaque
data:
  url-micro-inventory: aHR0cDovL3NlcnZpY2VzLWludmVudG9yeS1zZXJ2aWNlczo4MDgxL3NlcnZpY2VzLWludmVudG9yeQ==
#  Services - Kubernetes
#    Namespace: default
#    Si estamos en diferentes NS:
#      http://{services}.{namespaces}:{port}
#      services-inventory.default:80
#    Si estamos en el mismo NS:
#      http://{services}:{port}
#      services-inventory.default:80
#  http://services-inventory-services:8081/services-inventory