CREATE TABLE FOOTBALL_MANAGER
(
    ID          BIGSERIAL PRIMARY KEY,
    NAME        TEXT NOT NULL,
    SURNAME     TEXT NOT NULL,
    AGE         INT NOT NULL,
    NICKNAME    TEXT NOT NULL
);
ALTER SEQUENCE FOOTBALL_MANAGER_ID_SEQ RESTART 1000;